# scripts/step3_2_vectordb.py
"""Upload embedded chunks to Weaviate (custom vectors; no argparse).

Assumptions:
- Embeddings are already generated by embed.py and saved as JSONL rows.
- Config (configs/default.yaml) provides:
    - paths.embeddings_dir (fallback: data/processed/embeddings)
    - vectordb.host/port/grpc_port/skip_init_checks/collection_name
    - embedding.vector_dimension
- Each JSONL row may contain `embedding` (List[float]) and fields matching our schema.

Usage:
    uv run python scripts/step3_2_vectordb.py
"""

from __future__ import annotations
import sys
from pathlib import Path
from typing import List, Dict, Any

# Make `src/` importable when running as a script
sys.path.append(str(Path(__file__).resolve().parents[1] / "src"))

from utils.logger import get_logger
from utils.config import load_config, get_section, resolve_path
from utils.files import read_jsonl
from graph.nodes.vectordb import (
    init_client,
    close_client,
    ensure_collection,
    upload_objects,
    count_objects,
)

logger = get_logger(__name__)


def _gather_embedded_rows(emb_dir: Path) -> List[Dict[str, Any]]:
    """Load all *.jsonl files from embeddings directory."""
    if not emb_dir.exists():
        raise FileNotFoundError(f"Embeddings directory not found: {emb_dir}")

    files = sorted(emb_dir.glob("*.jsonl"))
    if not files:
        raise FileNotFoundError(f"No JSONL files found under: {emb_dir}")

    rows: List[Dict[str, Any]] = []
    for fp in files:
        data = read_jsonl(str(fp))
        if not data:
            logger.warning(f"[WARN] Empty file skipped: {fp}")
            continue
        rows.extend(data)
        logger.info(f"[INFO] Loaded {len(data)} rows from {fp.name}")

    if not rows:
        raise RuntimeError("No embedded rows were loaded; check your embed step outputs.")
    return rows


def main() -> None:
    """Connect, ensure collection, upload objects with vectors, and verify count."""
    cfg = load_config()
    psec = get_section(cfg, "paths")
    vsec = get_section(cfg, "vectordb")
    esec = get_section(cfg, "embedding")

    # Resolve embeddings directory (fallback to default path)
    try:
        emb_dir = resolve_path(cfg, "paths", "embeddings_dir")
    except Exception:
        emb_dir = Path("data/processed/embeddings")

    collection_name = vsec.get("collection_name", "FinancialDocChunk")
    vector_dim = int(esec.get("vector_dimension", 2560))

    logger.info(f"[STEP 1] Loading embedded rows from {emb_dir}")
    rows = _gather_embedded_rows(emb_dir)
    with_vec = sum(1 for r in rows if r.get("embedding") is not None)
    logger.info(f"[INFO] Total rows: {len(rows)} (with vectors: {with_vec})")

    logger.info("[STEP 2] Connecting to Weaviate")
    client = init_client()

    try:
        logger.info(f"[STEP 3] Ensuring collection '{collection_name}' (dim={vector_dim})")
        ensure_collection(client, name=collection_name, vector_dim=vector_dim)

        logger.info(f"[STEP 4] Uploading {len(rows)} objects to '{collection_name}'")
        upload_objects(
            client=client,
            collection_name=collection_name,
            objects=rows,
            batch_size=100,
            concurrent_requests=4,
        )

        logger.info(f"[STEP 5] Counting objects in '{collection_name}'")
        total = count_objects(client, collection_name)
        logger.info(f"[OK] Collection '{collection_name}' total objects: {total}")

    finally:
        close_client(client)


if __name__ == "__main__":
    main()